# # docker-compose.yml
services:
  backend:
    build:
      context: ./chronika
    container_name: chronikaapi-backend
    env_file:
      - ./chronika/.env.production
    environment:
      - DJANGO_ENV=production
      - EMBEDDINGS_MODEL_ID=BAAI/bge-m3
      - EMBEDDINGS_MODEL_PATH=/app/models/embeddings/bge-m3
      - EMBEDDINGS_CACHE_DIR=/app/.hf-cache
      - EMBEDDINGS_DEVICE=cpu
      - EMBEDDINGS_TRUST_REMOTE_CODE=false
    expose:
      - "8000"
    networks:
      - appnet
    volumes:
      - ./models:/app/models
      - hf_cache:/app/.hf-cache

  frontend:
    build:
      context: ./frontend
    container_name: chronikaapi-frontend
    volumes:
      - frontend_dist:/app/dist_volume
    command: sh -c "cp -r /app/dist/. /app/dist_volume/ && echo 'Frontend files copied to volume' && sleep infinity"
    networks:
      - appnet
    # НЕ пробрасываем порты наружу — nginx будет единственной точкой входа

  nginx:
    image: nginx:stable-alpine
    container_name: chronikaapi-nginx
    ports:
      - "80:80"
    volumes:
      - frontend_dist:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - appnet

  db:
    image: pgvector/pgvector:pg16
    container_name: chronikaapi-db
    restart: always
    environment:
      POSTGRES_DB: chronika
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appnet

volumes:
  frontend_dist:
    driver: local
  pgdata:
    driver: local
  hf_cache:
    driver: local

networks:
  appnet:
    driver: bridge