# Generated by Django 5.1.3 on 2026-03-30 13:21

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_calendar_id_usercalendar_google_calendar_id_and_more'),
        ('tasks', '0005_task_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('google_event_id', models.CharField(blank=True, help_text='ID события в Google Calendar', max_length=256, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('summary', models.CharField(blank=True, help_text='Название события', max_length=256, null=True)),
                ('description', models.TextField(blank=True, help_text='Описание события', null=True)),
                ('start', models.DateTimeField(blank=True, help_text='Дата начала события', null=True)),
                ('end', models.DateTimeField(blank=True, help_text='Дата окончания события', null=True)),
                ('htmlLink', models.URLField(blank=True, help_text='Ссылка на событие в Google Calendar', null=True)),
                ('organizer_email', models.EmailField(blank=True, help_text='Email организатора', max_length=254, null=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='tasks.task')),
                ('user_calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.usercalendar')),
            ],
            options={
                'ordering': ['start'],
                'constraints': [models.UniqueConstraint(fields=('user_calendar', 'google_event_id'), name='unique_event_id_when_user_calendar_id_is_not_null')],
            },
        ),
    ]
