# Generated by Django 5.1.3 on 2026-03-30 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='embedding',
        ),
    ]
