# Generated by Django 5.1.3 on 2026-04-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_embedding_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='htmlLink',
            field=models.URLField(blank=True, help_text='Ссылка на событие в Google Calendar', max_length=2048, null=True),
        ),
    ]
