# Generated by Django 5.1.3 on 2026-05-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_htmllink_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='htmlLink',
            field=models.URLField(blank=True, help_text='Ссылка на событие в Google Calendar', max_length=1024, null=True),
        ),
    ]
