# Generated by Django 5.1.3 on 2026-05-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_backfill_missing_updated_at_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantmessage',
            name='blocks',
            field=models.JSONField(blank=True, default=list, help_text='UI-блоки ответа ассистента (протокол чата).'),
        ),
        migrations.AlterField(
            model_name='assistantsession',
            name='action_plan',
            field=models.JSONField(blank=True, help_text='Текущий план действий (сериализация ActionPlan).', null=True),
        ),
        migrations.AlterField(
            model_name='assistantsession',
            name='dialog_context',
            field=models.JSONField(blank=True, default=dict, help_text='Структурированный контекст (disambiguation_options, last_interaction, …).'),
        ),
        migrations.AlterField(
            model_name='assistantsession',
            name='dialog_state',
            field=models.CharField(default='idle', help_text='Состояние FSM (idle, waiting_confirmation, …).', max_length=64),
        ),
        migrations.AlterField(
            model_name='assistantsession',
            name='last_referenced_id',
            field=models.BigIntegerField(blank=True, help_text='Последний выбранный object_id (задача/событие).', null=True),
        ),
    ]
