# Generated by Django 5.1.3 on 2026-03-30 13:21

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True),
        ),
    ]
