# Generated by Django 5.1.3 on 2026-03-30 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='embedding',
        ),
    ]
