# Generated by Django 5.1.3 on 2026-03-30 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_rename_task_timestamps'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeLog',
        ),
    ]
