# Generated by Django 5.1.3 on 2026-04-01 15:28

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_delete_timelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True),
        ),
    ]
