# Generated by Django 5.1.3 on 2026-04-02 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_task_embedding'),
    ]

    operations = []
