# Generated by Django 5.1.3 on 2026-04-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_task_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='embedding_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=10),
        ),
    ]
